
default:
  image: docker:20.10
  services:
    - docker:20.10-dind
  tags:
    - docker


stages:
  - schemes_validation
  - push_to_main


variables:
  GITLAB_PROJECT_NAME: colibri
  GITLAB_PROJECT_URL: scm.cstb.fr/dee/colibri.git
  GITLAB_PUSH_BRANCH_NAME: main
  JOB_IMAGE_URL: $DOCKER_GRP/python:3.11.6-slim-bookworm

job_schemes_validation:
  stage: schemes_validation
  image: $JOB_IMAGE_URL
  script:
    - pip3 install --upgrade pip
    - pip3 install --no-cache-dir -r $CI_PROJECT_DIR/requirements.txt
    - pip3 install $CI_PROJECT_DIR
    - python3 $CI_PROJECT_DIR/colibri/datamodel/utils/schemes_validator.py


job_push_to_main:
  stage: push_to_main
  image: $JOB_IMAGE_URL
  script:
    # Update
    - apt-get update
    # Add git
    - apt-get install -y git
    - git config --global user.name "${GITLAB_USER_EMAIL}"
    - git config --global user.email "${GITLAB_USER_NAME}"
    # Clone main branch to update from 1-edit-main
    - mkdir /tmp/main_branch_directory
    - cd /tmp/main_branch_directory
    - git clone --branch $GITLAB_PUSH_BRANCH_NAME https://gitlab-ci-token:$CI_JOB_TOKEN@$GITLAB_PROJECT_URL
    - cd $GITLAB_PROJECT_NAME
    - cp -r $CI_PROJECT_DIR .
    # Commit all modifications, then push them to the main branch
    - git add .
    # - git commit -m "[CONFIGURATION] Mise à jour des fichiers de configuration (json) pour le projet renoptim/backend"
    # - git push -o ci.skip https://$PAT_NAME:$PAT_VALUE@$RENOPTIM_BACKEND_GITLAB_PROJECT_URL $CI_COMMIT_BRANCH
  only:
    - 1-edit-main
