stages:
  - test

default:
  image: docker:20.10
  services:
    - docker:20.10-dind
  tags:
    - docker

test_job:
  stage: test
  image: continuumio/miniconda3
  before_script:
    - conda env create -f ci/environment.yml
    - source activate colibri
  script:
    - pytest -s --cov tests/ --cov-config=.coveragerc --cov-report term --cov-report xml:coverage.xml --junitxml=junit_report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week

