name: Publish Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust as needed

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc
          pip install .[doc]  # Same as in your GitLab CI config

      - name: Build documentation with Sphinx
        run: sphinx-build docs/source public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # Branch where GitHub Pages will be hosted

