default:
  image: docker:25.0
  services:
    - docker:25.0-dind
  tags:
    - docker


stages:
  - schemes_validation
  - test


variables:
  GITLAB_PROJECT_NAME: colibri
  GITLAB_PROJECT_URL: scm.cstb.fr/dee/colibri.git
  GITLAB_PUSH_BRANCH_NAME: main
  JOB_IMAGE_URL: $DOCKER_GRP/python:3.11-slim


job_schemes_validation:
  stage: schemes_validation
  image: $JOB_IMAGE_URL
  script:
    - pip3 install --upgrade pip
    - pip3 install --no-cache-dir -r $CI_PROJECT_DIR/requirements.txt
    - pip3 install $CI_PROJECT_DIR
    - python3 $CI_PROJECT_DIR/colibri/datamodel/utils/schemes_validator.py

job_test:
  stage: test
  image: continuumio/miniconda3
  before_script:
    - conda env create -f ci/environment.yml
    - source activate colibri
  script:
    - pytest -s --cov colibri/tests/ --cov-config=.coveragerc --cov-report term --cov-report xml:coverage.xml --junitxml=junit_report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week

