stages:
  - test

test_job:
  stage: test
  image: continuumio/miniconda3
  before_script:
    - conda env create -f environment.yml
    - conda activate colibri
  script:
    - pytest --cov=colibrisuce tests/
  artifacts:
    paths:
      - coverage.xml
      - htmlcov/
