stages:
  - test

default:
  image: docker:20.10
  services:
    - docker:20.10-dind
  tags:
    - docker

test_job:
  stage: test
  image: continuumio/miniconda3
  before_script:
    - conda env create -f ci/environment.yml
    - conda activate colibri
  script:
    - pytest --cov=colibrisuce tests/
  artifacts:
    paths:
      - coverage.xml
      - htmlcov/
