name : colibri
dependencies :
    - python=3.10
    - pandas
    - matplotlib
    - pytest
    - pytest-cov
    - scipy
    - networkx
    - ephem
    - jsonschema
    - pip
    - pip:
        - pvlib